### ISSUE TITLE
Increase cooldown on !strims

### ISSUE THREAD

**Issue by PinkishCow** [destinygg/bot#3]
I feel that increasing the cooldown on !strims is greatly needed to cut down on the mess retards using it every 10 seconds cause in chat. Increasing the cooldown would cause people to actually scroll up to find the links or just go to overrustle.com, instead of spamming !strims and having the bot throw out another 3 lines it posted a moment earlier.

**Comment by cene-co-za** [comment]
+1

**Comment by sztanpet** [comment]
worthless comments will be deleted, show support by using the feature dedicated to it ("Add your reaction")

**Comment by dharmaturtle** [comment]
Fixed in https://github.com/destinygg/bot/commit/1af2506f9ed84a32b4cd106356a68b2451cb6dff . Bot messages 3 lines long will result in a delay of 20s instead of 10s.
